#!/bin/sh
#
# @name BiCopter
#
# @type MultiRotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
# need to figure out the model location
PX4_SIM_MODEL=${PX4_SIM_MODEL:=Bicopter}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 8
param set-default CA_ROTOR_COUNT 2

param set-default CA_ROTOR0_PX 0.5
param set-default CA_ROTOR0_PY 0.0
param set-default CA_ROTOR1_PX -0.5
param set-default CA_ROTOR1_PY 0.0

param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR1_TILT 2

param set-default CA_ROTOR_COUNT 2
param set-default CA_SV_TL0_MAXA 45.0000
param set-default CA_SV_TL0_MINA -45.0000
param set-default CA_SV_TL0_TD 90
param set-default CA_SV_TL1_MAXA 45.0000
param set-default CA_SV_TL1_MINA -45.0000
param set-default CA_SV_TL1_TD 90
param set-default CA_SV_TL_COUNT 2

param set-default SIM_GZ_EC_FUNC1 101 #Motor 1
param set-default SIM_GZ_EC_FUNC2 102 #Motor 2
param set-default SIM_GZ_SV_FUNC1 201 #Servo 1
param set-default SIM_GZ_SV_FUNC2 202 #Servo 2

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000

param set-default MPC_THR_HOVER 0.60
