#!/bin/sh
#
# @name FireEagle2
#
# @type Multirotor with Tilt
# @class Multirotor
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Servo1 yaw servo
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 15

param set-default CA_AIRFRAME 8
# Tricopter
param set-default CA_ROTOR0_PX 0.5
param set-default CA_ROTOR0_PY 0.0
param set-default CA_ROTOR1_PX -0.5
param set-default CA_ROTOR1_PY 0.0

param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR1_TILT 2

param set-default CA_ROTOR_COUNT 2
param set-default CA_SV_TL0_MAXA 45.0000
param set-default CA_SV_TL0_MINA -45.0000
param set-default CA_SV_TL0_TD 90
param set-default CA_SV_TL1_MAXA 45.0000
param set-default CA_SV_TL1_MINA -45.0000
param set-default CA_SV_TL1_TD 90
param set-default CA_SV_TL_COUNT 2

# set servo on AUX2 to reverse. This is a bitmask 2=0000000010
param set-default PWM_AUX_REV 2
